# Generated by Django 4.1.dev20211210161305 on 2022-02-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0085_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('cd', 'Chardonnay'), ('pn', 'Pinot Noir'), ('sb', 'Sauvignon Blanc'), ('mt', 'Merlot'), ('sy', 'Syrah'), ('mc', 'Malbec'), ('sh', 'Shiraz'), ('pb', 'Pinot Blanc'), ('cs', 'Cabernet Sauvignon'), ('cf', 'Cabernet Franc')], max_length=67),
        ),
    ]
