# Generated by Django 4.0.2 on 2022-02-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0086_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('sh', 'Shiraz'), ('sb', 'Sauvignon Blanc'), ('wine', 'Wine'), ('pn', 'Pinot Noir'), ('sy', 'Syrah'), ('mc', 'Malbec'), ('cd', 'Chardonnay'), ('cs', 'Cabernet Sauvignon'), ('pb', 'Pinot Blanc'), ('cf', 'Cabernet Franc')], max_length=67),
        ),
    ]
