# Generated by Django 4.0.2 on 2022-02-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0092_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('wines', 'Wines'), ('clocks', 'Clocks'), ('furniture', 'Furniture'), ('painting', 'Paintings'), ('phones', 'Phones')], max_length=67),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/'),
        ),
    ]
