# Generated by Django 4.0.2 on 2022-02-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0093_alter_listing_category_alter_listing_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('wines', 'Wines'), ('furniture', 'Furniture'), ('phones', 'Phones'), ('painting', 'Paintings'), ('clocks', 'Clocks')], max_length=67),
        ),
    ]
