# Generated by Django 4.0.2 on 2022-02-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0094_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('painting', 'Paintings'), ('furniture', 'Furniture'), ('clocks', 'Clocks'), ('wines', 'Wines'), ('phones', 'Phones')], max_length=67),
        ),
    ]
