# Generated by Django 4.0.2 on 2022-02-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0098_alter_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('furniture', 'Furniture'), ('painting', 'Paintings'), ('phones', 'Phones'), ('wines', 'Wines'), ('clocks', 'Clocks')], max_length=67),
        ),
    ]
