# Generated by Django 4.1.dev20211210161305 on 2022-02-11 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0100_alter_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='idUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('clocks', 'Clocks'), ('painting', 'Paintings'), ('furniture', 'Furniture'), ('phones', 'Phones'), ('wines', 'Wines')], max_length=67),
        ),
    ]
