# Generated by Django 4.1.dev20211210161305 on 2022-02-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0109_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('clocks', 'Clocks'), ('painting', 'Paintings'), ('wines', 'Wines'), ('phones', 'Phones'), ('furniture', 'Furniture')], max_length=67),
        ),
    ]
